install:
  - ps: |
      if ($env:PLATFORM -eq "x86") {
        Start-FileDownload 'https://static.rust-lang.org/dist/rust-1.0.0-i686-pc-windows-gnu.exe' -FileName rust.exe
      } else {
        Start-FileDownload 'https://static.rust-lang.org/dist/rust-1.0.0-x86_64-pc-windows-gnu.exe' -FileName rust.exe
      }
  - rust.exe /VERYSILENT /NORESTART /DIR="C:\Program Files\Rust"
  - SET PATH=%PATH%;C:\Program Files\Rust\bin
  - rustc -vV
  - cargo -V
  - git submodule update --init --recursive

platform:
  - x86
  - x64

build: false

test_script:
  - cargo test --verbose
