disallowed-methods = [
    { path = "web_sys::window", reason = "is not available in every context" },
    { path = "web_sys::HtmlCanvasElement::width", reason = "Winit shouldn't touch the internal canvas size" },
    { path = "web_sys::HtmlCanvasElement::height", reason = "Winit shouldn't touch the internal canvas size" },
    { path = "web_sys::HtmlCanvasElement::set_width", reason = "Winit shouldn't touch the internal canvas size" },
    { path = "web_sys::HtmlCanvasElement::set_height", reason = "Winit shouldn't touch the internal canvas size" },
    { path = "web_sys::Window::document", reason = "cache this to reduce calls to JS" },
    { path = "web_sys::Window::get_computed_style", reason = "cache this to reduce calls to JS" },
    { path = "web_sys::HtmlElement::style", reason = "cache this to reduce calls to JS" },
    { path = "web_sys::Element::request_fullscreen", reason = "Doesn't account for compatibility with Safari" },
    { path = "web_sys::Document::exit_fullscreen", reason = "Doesn't account for compatibility with Safari" },
    { path = "web_sys::Document::fullscreen_element", reason = "Doesn't account for compatibility with Safari" },
    { path = "objc2_app_kit::NSView::visibleRect", reason = "We expose a render target to the user, and visibility is not really relevant to that (and can break if you don't use the rectangle position as well). Use `frame` instead." },
    { path = "objc2_app_kit::NSWindow::setFrameTopLeftPoint", reason = "Not sufficient when working with Winit's coordinate system, use `flip_window_screen_coordinates` instead" },
]
