# documentation: https://github.com/crate-ci/typos/blob/master/docs/reference.md

[default.extend-identifiers]
TME_LEAVE = "TME_LEAVE"             # From windows_sys::Win32::UI::Input::KeyboardAndMouse::TME_LEAVE
XF86_Calculater = "XF86_Calculater" # From xkbcommon_dl::keysyms::XF86_Calculater
ptd = "ptd"                         # From windows_sys::Win32::System::Com::FORMATETC { ptd, ..}
requestor = "requestor"             # From x11_dl::xlib::XSelectionEvent { requestor ..}
